---
env:
  browser: true
  es2020: true
extends:
  - 'eslint:recommended'
  - 'airbnb-base'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:import/typescript'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
  - jest
rules:
  import/extensions:
    - 'error'
    - 'ignorePackages'
    - ts: never
overrides:
  - files: ['**/*.test.ts']
    env:
      jest/globals: true
